### ISSUE TITLE
Event dot is invisible when the specific day cell is selected

### ISSUE THREAD

**Issue by nbnsresta** [PoskOfficial/Miti#71]
**Describe the bug**
Due to the color similarity of colors between cell background and event indicator, the dot becomes invisible when the cell is selected.

**To Reproduce**
1. Open the calendar view
2. Click on a day containing an event
3. The indicator is now invisible

**Expected behavior**
The indicator should turn white.

**Comment by nirajacharyaa** [comment]
@nbnsresta thank you for opening an issue. It is not invisible but the dot and the selection indicator has very less contrast. Can you create a PR that fixes this issue?

**Comment by nbnsresta** [comment]
@nirajacharyaa Its taking some time for the Space dev mode to be enabled. Ill get back to it.
