### ISSUE TITLE
Replace vite logo with miti app logo in title bar

### ISSUE THREAD

**Issue by maskudo** [PoskOfficial/Miti#76]
**Describe the bug**
The title bar currently shows vite logo. Replace it with the miti app logo.

**To Reproduce**
1. Go to https://miti.bikram.io/
2. The title bar has vite logo.

**Expected behavior**
The title bar must have the miti app logo.

**Screenshots**
![image](https://github.com/user-attachments/assets/495e2c2e-8ac5-43c0-b90d-1a5697a71875)

**Desktop (please complete the following information):**
 - OS: [nixos]
 - Browser [firefox]

**Comment by nirajacharyaa** [comment]
I appreciate your concern, will remove this soon.
